version: "3.9"

services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      # If n8n needs to access Qdrant later:
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ../:/workspace # <- this mounts the RAG/ repo as /workspace inside the n8n container
      - ./data:/home/node/.n8n
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5678/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - ragnet

networks:
  ragnet:
    external: true
