version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"
    volumes:
      - ${QDRANT_DATA_PATH:-./data}:/qdrant/storage
      - ${QDRANT_SNAPSHOTS_PATH:-./snapshots}:/qdrant/snapshots
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - ragnet

networks:
  ragnet:
    external: true
